[language-server.deno-ls]
command = "deno"
args = ["lsp"]
config = { enable = true, unstable = true }

[[language]]
name = "typescript"
language-servers = ["deno-ls"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["deno-ls", "tailwindcss-ls", "emmet-ls"]
auto-format = true
